name: Publish to itch.io

on:
  release:
    types: [released]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows-64, web]
        include:
          - platform: windows-64
            target: x86_64-pc-windows-gnu
            executable_name: "${{ vars.KEBAB_CASE_GAME_NAME }}.exe"
          - platform: web
            target: wasm32-unknown-unknown

    steps:
      - uses: actions/checkout@v4

      - name: Install MinGW toolchain
        if: matrix.target == 'x86_64-pc-windows-gnu'
        run: sudo apt-get update; sudo apt-get install -y gcc-mingw-w64-x86-64

      - uses: dtolnay/rust-toolchain@1.86.0
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ vars.CACHE_BUILD_VERSION }}-cargo
          shared-key: ${{ matrix.platform }}-release
          # Only save if we're running on the main branch, so that other branches can also use this cache.
          save-if: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      - name: Install tools for WASM build
        if: matrix.platform == 'web'
        # TODO: Update this once a new version with wasm-opt flag customization gets released
        run: |
          cargo install --git https://github.com/TheBevyFlock/bevy_cli --branch main --rev 0a4df19a729dbbb83774c4ddacf21770bafceb21 --locked bevy_cli

      - name: Install alsa and udev
        if: ${{ runner.os == 'linux' }}
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev

      - name: Build release
        if: matrix.platform == 'web'
        run: bevy build --yes --release web --bundle

      - name: Build release
        if: matrix.platform != 'web'
        run: cargo build --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        if: matrix.platform == 'web'
        with:
          name: ${{ matrix.platform }}
          path: |
            ./target/bevy_web/web-release/${{ vars.KEBAB_CASE_GAME_NAME }}/*

      - uses: actions/upload-artifact@v4
        if: matrix.platform != 'web'
        with:
          name: ${{ matrix.platform }}
          # We don't need to publish the `assets` folder alongside the binary as we are using bevy_embedded_assets
          path: |
            ./target/${{ matrix.target }}/release/${{ matrix.executable_name }}

  publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    strategy:
      matrix:
        platform: [windows-64, web]
    steps:
      - name: Download and check butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - run: mkdir release

      - name: Download ${{ matrix.platform }} release artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: ./release

      - name: Publish game with butler
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          ./butler push ./release/ ${{ vars.ITCH_IO_USERNAME }}/${{ vars.KEBAB_CASE_GAME_NAME }}:${{ matrix.platform }} --userversion ${{ github.event.release.tag_name }}
